### PR TITLE
BeatInfo support

### PR DESCRIPTION
**Pull request by mhite**
Implements BeatInfo protocol on Stagelinq devices.

See https://github.com/icedream/go-stagelinq/issues/9

### CODE REVIEW

**Comment by mhite** [comment]
How are you feeling about the PR @icedream ?

**Review by icedream — APPROVED** [review]
LGTM, even got testing in there. 👍🏻 Will merge it later.

**Comment by icedream** [comment]
Obviously, sorry for the delays on my end on this, this project is unfortunately still far outside of my focus zone right now but I will continue to try and merge stuff as it comes in for this project!

**Comment by mhite** [comment]
@icedream - Thanks for keeping the project going! It's very much appreciated and has inspired so much exploration and experimentation in the community.

**Pull request merged**
